<a href="https://colab.research.google.com/github/shaun3asfas/2026-QB-BDA-code/blob/main/code/03w_numpy_handle_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. 패키지 numpy 개요와 자료형 ndarray

In [ ]:
import numpy as np
a = np.ndarray(shape=(2,2), dtype=int)
a

array([[      495451975,               0],
       [136381489506672,        11687896]])

In [ ]:
a = np.array([1,2,3], dtype=int)
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [ ]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [ ]:
a.data

In [ ]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [ ]:
lang = np.array(['파이썬', '자바', '씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [ ]:
a = np.array((1,2,3), dtype=float)
a

array([1., 2., 3.])

In [ ]:
b = np.array((1, 2.5, 3))
b

array([1. , 2.5, 3. ])

#2. 내장함수 arange()외 linspace()

In [2]:
import numpy as np
print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [3]:
print(np.arange(2.0))
print(np.arange(2.0, 6.5 ))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [4]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.reshape(a, (2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [8]:
b = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
np.reshape(b, (2,-1))

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [11]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [12]:
print( (3-2) / (50-1))

0.02040816326530612


In [13]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [14]:
print( (3-2) / 50)

0.02


In [15]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [16]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [17]:
np.arange(0.1, 0.4, 0.1)

array([0.1, 0.2, 0.3, 0.4])

In [18]:
np.arange(1,4,1) / 10

array([0.1, 0.2, 0.3])

In [19]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [20]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

#3. 내장함수 zeros()와 ones(), empty()

In [24]:
import numpy as np
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [22]:
a.dtype

dtype('float64')

In [26]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [27]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [28]:
b.shape

(2, 1)

#####원소가 모두 1인 배열을 생성하는 ones()

In [29]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

#####대각선 원소가 모두 1인 2차원 배열을 생성하는 eye()

In [31]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [33]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [34]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
a = np.eye(3, 4, -1)
a

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

#####원소가 모두 1인 배열을 생성하는 full()

In [36]:
import numpy as np
np.full([2,3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [37]:
np.full([2,3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [38]:
np.full([3,4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [39]:
np.full([4,3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

######원소가 모두 1인 배열을 생성하는 empty()

In [40]:
import numpy as np
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [41]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [42]:
np.empty([2, 3], dtype=int)

array([[4611686018427387904, 4613487458278336102, 4615288898129284300],
       [4616639978017495449, 4617540697942969548, 4618441417868443647]])

#####원소값이 0인 주어진 형태의 배열을 생성하는 zeros_like()

In [44]:
import numpy as np
a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#####원소값이 1인 주어진 형태의 배열을 생성하는 ones_like()

In [45]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

#####원소값이 주어진 값이며 주어진 형태의 배열을 생성하는 full_like()

In [46]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

#4. 배열 연산

#####배열과 스칼라와의 연산

In [47]:
import numpy as np
a = np.arange(3)
a

array([0, 1, 2])

In [51]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


#####배열과 배열의 연산

In [53]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [55]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [56]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [57]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [59]:
b += a
b

array([0.5, 3.5, 6.5, 9.5])

In [60]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [61]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [62]:
a @ b #두 배열의 곱 연산

array([[12,  6],
       [12,  6]])

In [63]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [64]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

#####배열 함수

In [65]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [66]:
a.sum()

np.int64(46)

In [67]:
a.sum(axis=0) #배열의 동일 열에서 세로로 더한 합

array([16, 30])

In [68]:
a.sum(axis=1) #배열의 동일 행에서 가로로 더한 합

array([30, 13,  3])

In [69]:
print(np.sum(a))
print(a.sum(axis=0))
print(a.sum(axis=1))

46
[16 30]
[30 13  3]


In [70]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [71]:
a.cumsum() #모든 원소를 순서대로 누적 합계 반환

array([ 3,  8, 16, 17, 19, 22])

In [73]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [74]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

#####범용 함수

In [76]:
a = np.array([1, 4, 9]) #코드 인자 1
np.sqrt(a)

array([1., 2., 3.])

In [77]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [78]:
a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [81]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [83]:
np.add(a, b) #코드 인자 2

array([ 3,  6, 11])

In [84]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [85]:
np.power(a, b)

array([ 1, 16, 81])

#5. 배열 슬라이싱과 형태수정

In [ ]:
import numpy as np
a = np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
a[3]

np.int64(9)

In [ ]:
int(a[3])

9

In [ ]:
a[-2]

np.int64(64)

In [ ]:
a[1:4]

array([1, 4, 9])

In [ ]:
a[-5:-1]

array([25, 36, 49, 64])

In [ ]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [ ]:
a= np.arange(24).reshape(2, 3, 4)#3 3차원배열
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
a[:,1,1]

array([ 5, 17])

In [ ]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[1, ... ,1]

array([13, 17, 21])

In [ ]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
b = np.arange(1, 13).reshape(3, 2, 2) #1차원 배열로 만드는 ndarray.ravel()
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

#6. 브로드캐스팅 개요

#####브로드캐스팅 개요

In [87]:
from numpy import array

a = array([3, 4, 5])
b = array([8, 7, 6])
a + b

array([11, 11, 11])

In [89]:
a = array([3, 4, 5, 7])   #두 배열의 모양이 다르면 ValueError 발생
b = array([8, 7, 6,])
#a * b

#####스칼라 또는 단일 값과 배열의 연산

In [90]:
a = array([3, 4, 5])
a

array([3, 4, 5])

In [91]:
b = 2
b

2

In [92]:
a + b

array([5, 6, 7])

In [94]:
from numpy import array

A = array([[1, 2, 3], [1, 2, 3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [95]:
A + 2

array([[3, 4, 5],
       [3, 4, 5]])

#####하나의 배열이 1차원으로 다른 배열 열수와 같은 구조의 브로드캐스팅

In [98]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [100]:
print(x * y)
print(x + y)

[[-1  0  3]
 [-4  0  6]
 [-7  0  9]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


#####하나의 배열이 1차원으로 다른 배열 행수와 같은 구조의 브로드캐스팅

In [101]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [103]:
print(x / y)
print(x - y)

[[0.33333333 0.66666667 1.        ]
 [0.66666667 0.83333333 1.        ]
 [0.77777778 0.88888889 1.        ]]
[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]


#####행 또는 열이 1인 두 배열의 브로드캐스팅

In [104]:
from numpy import arange

x = arange(1, 4)
x

array([1, 2, 3])

In [105]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [106]:
print(x*y)
print(x-y)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]


In [107]:
x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [108]:
y = arange(1, 3)
y

array([1, 2])

In [109]:
print(x*y)
print(x+y)

[[ 0  0]
 [ 3  6]
 [ 6 12]
 [ 9 18]]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


#####상수 np.newaxis 활용해 두 배열의 브로드캐스팅

In [129]:
x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [117]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [126]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [132]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [131]:
b = array([1, 2, 3])
b

array([1, 2, 3])

In [134]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [136]:
a*b #교재 오타 x*y 오류

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

#7. 고급 색인

#####1차원 배열의 색인

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(x[1])

1


In [ ]:
print(x[:5])

[0 1 2 3 4]


In [ ]:
print(x[[2]])

[2]


In [ ]:
print([[2,3]])

[[2, 3]]


In [ ]:
x[[2,3,5,8]]

array([2, 3, 5, 8])

In [ ]:
x[np.array([5,3,-4,8])]

array([5, 3, 6, 8])

In [ ]:
x = np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[5]

array([40, 41, 42, 43, 44, 45, 46, 47])

In [ ]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[[0], [1]]

array([1])

In [ ]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[:, [5,4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [ ]:
x[[1,3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x[[1,3],:]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x[[5,4], :]

array([[40, 41, 42, 43, 44, 45, 46, 47],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
x[[3],[2]]

array([26])

In [ ]:
x[[1,3], [2,2]]

array([10, 26])

In [ ]:
x[[4,6], [6,4]]

array([38, 52])

In [ ]:
x[[1,3], [2]]

array([10, 26])

In [ ]:
x[[1,3],2]

array([10, 26])

In [ ]:
x[[0,2,4],[1]]

array([ 1, 17, 33])

In [ ]:
x[[0,2,4],:2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
a = np.arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[[2,3,4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[[2,3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[np.arange(2,5)][:, [1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [ ]:
a[np.arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[np.arange(2,5)][:, np.arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])