<a href="https://colab.research.google.com/github/shaun3asfas/2026-QB-BDA-code/blob/main/code/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. 배열 결합

###numpy.vstack()

In [2]:
import numpy as np
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
import numpy as np
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [5]:
c = np.arange(20, 24).reshape(2, 2)
c

array([[20, 21],
       [22, 23]])

In [6]:
np.vstack((a,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [7]:
np.vstack((a, b, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [8]:
d = np.array([100, 200])
np.vstack((a, d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [9]:
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

###numpy.hstack()

In [10]:
a - np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
np.hstack((a, b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [12]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [122]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [125]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [126]:
b = np.arange(10, 22).reshape(3, 4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [127]:
np.column_stack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [128]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [130]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [131]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [132]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [133]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [134]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [135]:
np.column_stack == np.hstack

False

#####numpy.concatenate()

In [143]:
import numpy as np
a = np.array(([1, 2]))
b = np.array(([3, 4]))
c = np.array(([5, 6]))

In [144]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [145]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [146]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [148]:
x = np.arange(6).reshape(2, 3)
print(x)

y = np.arange(10, 16).reshape(2, 3)
print(y)

z = np.arange(20, 24).reshape(2, 2)
print(z)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
[[20 21]
 [22 23]]


In [149]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [151]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [152]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [153]:
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

#####numpy.row_stack()

In [137]:
import numpy as np
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [138]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [139]:
np.row_stack((a, b))

/tmp/ipykernel_2119/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [140]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [141]:
a = np.array([4., 2., 1.])
b = np.array([3., 8., 7.])
print(np.row_stack((a, b)))
print(np.vstack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]
[[4. 2. 1.]
 [3. 8. 7.]]


/tmp/ipykernel_2119/290897912.py:3: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a, b)))


In [142]:
np.row_stack == np.vstack #함수 np.row_stack과 np.vstack의 결과는 항상 같다

False

In [15]:
import numpy as np
a = np.arange(1, 13).reshape(3, 4)
c = np.arange(1, 6, 2)
a, c

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([1, 3, 5]))

In [16]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [17]:
np.expand_dims(c, axis=1)

array([[1],
       [3],
       [5]])

In [18]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [19]:
np.column_stack((a,c))  #page23 ppt

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [20]:
a = np.arange(1, 4)
b = np.arange(4, 7)
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [21]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
np.c_[a, b]
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
x = np.arange(1, 4).reshape(1, 3)
y = np.arange(4, 7).reshape(1, 3)
x, y

(array([[1, 2, 3]]), array([[4, 5, 6]]))

In [24]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [25]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [26]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [154]:
import numpy as np
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [155]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [156]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [157]:
np.hstack((a, c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [158]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [159]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [160]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [161]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [162]:
np.row_stack((a, b))

/tmp/ipykernel_2119/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [163]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [164]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [165]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [168]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [170]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])

In [171]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [173]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [174]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [175]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

#####여러 1차원 배열을 수평 방향으로 합치는 방법

In [176]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [177]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [179]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [180]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

#####여러 1차원 배열을 수직 방향으로 합치는 방법

In [181]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [182]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [183]:
np.row_stack((a, b))

/tmp/ipykernel_2119/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [185]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [187]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

#####여러 1차원배열을 행으로 확장해 수평 방향으로 합치는 방법

In [188]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [189]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [191]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [192]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [193]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

#2. 배열의 분리

###np.split(ary, n)

In [27]:
import numpy as np
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [28]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [29]:
print(type(s))
print(s[0])

<class 'list'>
[0. 1. 2.]


###np.split(ary, [i, j, k...])

In [30]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [32]:
np.split(y, [2, 3, 4])

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [33]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [34]:
y[4:6]

array([50, 60])

In [35]:
y[6:]

array([], dtype=int64)

###다차원 배열 np.hsplit(ary, n)

In [36]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [37]:
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [38]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [39]:
np.split(a, [3, 5, 7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [40]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [42]:
np.split(b, [2, 4, 6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

###분할 함수 hsplit()과 vsplit()

#####np.hsplit(ary)

In [43]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [45]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [46]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [47]:
np.hsplit(a, 3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [48]:
np.hsplit(a, 4)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [49]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [50]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [51]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

#####np.vsplit(ary)

In [52]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
#np.vsplit(a, 2) #수직으로의 분할은 2차원 이상의 배열에서만 가능하다

In [54]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [55]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [56]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [57]:
a[:1, :]

array([[0, 1, 2]])

In [58]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [59]:
a[6:, :]

array([], shape=(0, 3), dtype=int64)

#####3차원 배열의 hsplit()

In [60]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [61]:
np.hsplit(x, 2) #두번째 축 분할 axis=1

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [62]:
np.split(x, 2, axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [63]:
x[:, :2, :]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]],

       [[24, 25],
        [26, 27]]])

In [64]:
x[:, 2:, :]

array([[[ 4,  5],
        [ 6,  7]],

       [[12, 13],
        [14, 15]],

       [[20, 21],
        [22, 23]],

       [[28, 29],
        [30, 31]]])

In [65]:
np.hsplit(x, [1,3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

#####3차원 배열의 vsplit()

In [66]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [67]:
np.vsplit(x, 2) #두번째 축 분할 axis=0방향

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [68]:
np.split(x, 2, axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [69]:
x[:2, :, :]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [70]:
x[2:, :, :]

array([[[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [71]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

#####np.array_split()개요

In [118]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [73]:
np.array_split(x, 2) #배열 x를 2개로 분할

[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]

In [74]:
np.array_split(x, 3) #배열 x를 3개로 분할

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [75]:
np.array_split(x, 4)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]

In [76]:
np.array_split(x, 5)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8.])]

In [77]:
np.array_split(x, [2, 4, 8])

[array([0., 1.]), array([2., 3.]), array([4., 5., 6., 7.]), array([8.])]

#####2차원 np.array_split() 분할

In [78]:
import numpy as np

a = np.arange(35).reshape(7, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [79]:
np.array_split(a, 2, axis=0) #배열을 수직으로 2개 나눔

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [80]:
np.array_split(a, 2, axis=1) #배열을 수평으로 2개 나눔

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22],
        [25, 26, 27],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [28, 29],
        [33, 34]])]

In [81]:
np.array_split(a, 4, axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34]])]

In [82]:
np.array_split(a, 4, axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22],
        [27],
        [32]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23],
        [28],
        [33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [83]:
np.array_split(a, [2, 4], axis=0) #수직으로 [2, 4]로 슬라이싱한 3개의 배열 목록 반환

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [84]:
np.array_split(a, [2, 4], axis=1) #수평으로 [2, 4]로 슬라이싱한 3개의 배열 목록 반환

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28],
        [32, 33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

#####3차원 이상에서 axis=2로 배열 분할

In [85]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [86]:
np.array_split(x, 4, axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [87]:
np.split(x, [2, 4, 5], axis=2)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [88]:
x[:, :, 5:]

array([[[ 5],
        [11]],

       [[17],
        [23]]])

#####함수 np.dsplit()

In [89]:
x = np.arange(24).reshape(2, 2, 6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [90]:
np.dsplit(x, 2) #무조건 axis=2로만 분리하는 함수

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [91]:
np.split(x, 2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [92]:
np.dsplit(x, 3)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4,  5],
         [10, 11]],
 
        [[16, 17],
         [22, 23]]])]

In [93]:
np.dsplit(x, [2, 4, 5])

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [94]:
x[:, :, 4:5]

array([[[ 4],
        [10]],

       [[16],
        [22]]])

#3. numpy의 난수와 다양한 함수

#####난수 제너레이터의 함수 random(), integers()

In [112]:
import numpy as np

rg = np.random.default_rng(1)
rg.random() #(0, 1) 실수 난수

0.5118216247002567

In [96]:
rg.random()

0.9504636963259353

In [97]:
rg.random((3,4))

array([[0.14415961, 0.94864945, 0.31183145, 0.42332645],
       [0.82770259, 0.40919914, 0.54959369, 0.02755911],
       [0.75351311, 0.53814331, 0.32973172, 0.7884287 ]])

#####난수 생성기 함수 integers()

In [98]:
import numpy as np

rg = np.random.default_rng(1)
rg.integers(1, 7, (3, 4)) #정수 난수

array([[3, 4, 5, 6],
       [1, 1, 5, 6],
       [2, 2, 6, 3]])

In [99]:
rg.integers(low=1, high=10, size=(2, 8))

array([[3, 8, 3, 4, 6, 5, 1, 1],
       [8, 7, 8, 5, 8, 3, 5, 8]])

In [100]:
rg.integers(1, 10, (2, 8))

array([[2, 3, 2, 5, 9, 2, 4, 4],
       [9, 2, 5, 3, 1, 7, 1, 3]])

#####난수 제너레이터의 함수 standard_normal()

In [101]:
import numpy as np

rg = np.random.default_rng(1)
rg.standard_normal(10) #표준 정규 분포

array([ 0.34558419,  0.82161814,  0.33043708, -1.30315723,  0.90535587,
        0.44637457, -0.53695324,  0.5811181 ,  0.3645724 ,  0.2941325 ])

In [102]:
rg.standard_normal((3, 4))

array([[ 0.02842224,  0.54671299, -0.73645409, -0.16290995],
       [-0.48211931,  0.59884621,  0.03972211, -0.29245675],
       [-0.78190846, -0.25719224,  0.00814218, -0.27560291]])

In [103]:
rg.standard_normal((10, 5))

array([[ 1.29406381,  1.00672432, -2.71116248, -1.88901325, -0.17477209],
       [-0.42219041,  0.213643  ,  0.21732193,  2.11783876, -1.11202076],
       [-0.37760501,  2.04277161,  0.646703  ,  0.66306337, -0.51400637],
       [-1.64807517,  0.16746474,  0.10901409, -1.22735205, -0.68322666],
       [-0.07204368, -0.94475162, -0.09826997,  0.09548303,  0.03558624],
       [-0.50629166,  0.59374807,  0.89116695,  0.3208483 , -0.81823023],
       [ 0.73165228, -0.50144002,  0.87916062, -1.07178742,  0.9144672 ],
       [-0.02006345, -1.24874889, -0.31389947,  0.05410228,  0.27279134],
       [-0.98218812, -1.10737305,  0.19958453, -0.46674962,  0.23550561],
       [ 0.75951952, -1.64878737,  0.25438812,  1.22464697, -0.29752684]])

In [104]:
np.set_printoptions(3)

In [105]:
np.random.rand(3)

array([0.602, 0.821, 0.101])

In [110]:
x = np.arange(1, 7).reshape(2, 3)
y = np.arange(7, 13).reshape(2, 3)
x, y

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [111]:
np.hstack((a, b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 7 and the array at index 1 has size 6

In [113]:
np.hstack((x, y))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [194]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [115]:
m = np.arange(24).reshape(2, 3, 4)
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [116]:
n = np.arange(96).reshape(4, 4, 6)
n

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]],

       [[72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95]]])

In [117]:
np.split(n, 2)[1].shape

(2, 4, 6)